include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = GreedPreferences

GreedPreferences_FILES = $(wildcard *.m)
GreedPreferences_FRAMEWORKS = UIKit
GreedPreferences_PRIVATE_FRAMEWORKS = Preferences
GreedPreferences_INSTALL_PATH = /Library/PreferenceBundles
GreedPreferences_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
